### ISSUE TITLE
请问下 这个适合什么版本？

### ISSUE THREAD

**Issue by Someant** [kevins1022/YunGouCMS#1]
另外你有这个程序的目录结构么？
我最近也可能会做二次开发？

**Comment by ning1022** [comment]
当时的3.*版本，具体的忘记了。以前我在那个公司做的。

**Comment by Someant** [comment]
我看了下 源码 简直了。。。MVC概念好模糊，各种地方穿插这sql查询语句

**Comment by ning1022** [comment]
你研究下吧，我记得当时那个银联的测试通过了。

**Comment by ning1022** [comment]
https://github.com/kevins1022/chinapay  看下这里，有个官网的demo,以前我用的。

**Comment by Someant** [comment]
我现在开发 并不是说 要加入支付接口  而是说 我要弄个商城 又有一元购 又有普通的商城功能

**Comment by ning1022** [comment]
那您就自己读下它的代码吧，云购算法很麻烦，祝你好运啦！

**Comment by GingJan** [comment]
代码结构好混乱，有人有兴趣用框架重写吗？

**Comment by Someant** [comment]
@zjien 重写个人肯定是没有啥兴趣的 招人写吧 要么就找开发这个系统的公司写
